name: "Create Staging Server"
on:
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
jobs:
  create_server:
    environment:
      name: billing-staging
      url: https://billing-staging.strut.so
    runs-on: ubuntu-20.04
    defaults: 
      run:
        shell: bash
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Add Homebrew to PATH
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: Setup EB CLI
        run: brew install aws-elasticbeanstalk
      - name: Initialize EB CLI
        run: eb init --region ca-central-1 strutt-billing-staging
      - name: Create Staging Env
        run: eb create strutt-billing-staging-1 --timeout 30 --verbose --process
